:rss_dler:
  period:           480   # feed check default interval time (in minutes)
  timeout:          15    # download/scrape timeout (in seconds)
  parse_timeout:    30    # rss parsing timeout (in seconds)
  max_item_days:    33    # number of required days for an item to be marked as old
  max_old_items:    100   # maximum number of old items to keep
  # item properties to be hashed for generating its unique id
  # available keys are: :id, :link, :title, :descr, :date
  hash_keys:
    - :id
    - :link
    - :title
    - :date

# ------------------------------------------------------------------------------

:rss_mngr:
  layout:           spartan     # layout css file
  port:             3333        # webserver (GUI) listening port
  check_interval:   5           # periodic feed check interval time (in minutes)
  exit_grace_time:  5           # feed download grace time on exit (in minutes)
  # every link will be called via ajax and appended to this one
  forward_url:      http://www.foobar.com:12345?url=
