#!/bin/bash

# take a look at this file, it defines useful variables and functions
source ../lib/functions.sh

# the script is called with three arguments
#   1. TIMEOUT
#   2. AGENT
#   3. BASEURL

function scrapeIt () {
  WGET -O - "$BASEURL" | \
    sanitizeHtml | \
    grep "\/comics\/" | \
    sed 's/.*src="\([^"]\+cad-\([0-9]\{4\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)[^"]\+\)".*alt="\([^"]\+\)".*/\1\n\2-\3-\4\n\5/' | \
    while read STRIP; read DATA; read TITLE; do
      cat <<XML
    <item>
      <title>$TITLE</title>
      <link>$STRIP</link>
      <guid isPermaLink="false">$DATA,$STRIP</guid>
      <description><![CDATA[<a href="$STRIP"><img border="0" src="$STRIP" /></a>]]></description>
      <pubDate>`getDate $DATA`</pubDate>
    </item>
XML
    done | \
    sanitizeXml
} # scrapeIt

printScrape "Feed Title" "$BASEURL"

